### ISSUE TITLE
Zoom in/Zoom Out buttons overlapping

### ISSUE THREAD

**Issue by alexanderthieme** [CovOpen/CovMapper#142]
Die Zoom in/out buttons sind neben der zugeklappten Infoxbox positioniert.

In Abhängigkeit von der Länge der Landkreisnamen überlappt die Box mit den Buttons

![Screenshot_2020-10-20-12-12-54-941_org mozilla firefox](https://user-images.githubusercontent.com/61984544/96573129-01effc80-12ce-11eb-8289-a6b1d35d2778.jpg)

**Comment by kommander** [comment]
Ich glaube die Landkreisnamen haben keine Auswirkung auf die Breite der Box, aber wir koennten die Zoom Buttons nach oben schieben wenn die Box offen ist auf mobile. Auf dem Desktop ist ja mehr Platz.

**Comment by alexanderthieme** [comment]
Buttons sollen ausgeblendet werden auf mobile

**Comment by ChristophWersal** [comment]
Die Buttons werden bereits ausgeblendet bei kleinen Bildschirmen. Bitte wieder öffnen falls es doch wieder auftritt.
