### ISSUE TITLE
Zoom to homelocation feature

### ISSUE THREAD

**Issue by alexanderthieme** [CovOpen/CovMapper#144]
Das "Zoom to homelocation feature" sollte nur einmal beim Start der App, bzw. beim Wiederbesuchen der Website ausgelöst werden.

Es wird jedoch jedes mal ausgelöst, wenn auf die Karte gewechselt wird.

Reproduzierbarkeit:
1.) Beliebigen nicht Home Landkreis auswählen
2.) Auf Fragen und Antworten im Menü gehen
3.) Zurück auf die Karte wechseln

**Comment by kommander** [comment]
Passiert im Moment on mount von der Komponente, @kantimam hatte das im Blick? Wir wollten glaube ich das dorthin Springen direkt nach PLZ Eingabe aufrufen, anstatt on mount.

**Comment by kommander** [comment]
#230 fixes this
