### ISSUE TITLE
Eingabe der PLZ in Welcome Flow ist ungültig

### ISSUE THREAD

**Issue by DanielHabenicht** [CovOpen/CovMapper#153]
![image](https://user-images.githubusercontent.com/13590797/96652472-3d72e100-1337-11eb-88d1-22069dbd1dc9.png)

Es ist nur das Feld, die PLZ existiert und wird über die Suche gefunden.

**Comment by ChristophWersal** [comment]
Ich habe den Regexp angepasst. Postleitzahlen die mit 0 beginnen sind nun auch erlaubt.

**Comment by DanielHabenicht** [comment]
Westler Problem ^
