### ISSUE TITLE
Map ist zweisprachig

### ISSUE THREAD

**Issue by DanielHabenicht** [CovOpen/CovMapper#154]
![WhatsApp Image 2020-10-20 at 10 25 17 PM](https://user-images.githubusercontent.com/13590797/96652773-defa3280-1337-11eb-965d-d5a4d45bbbc8.jpeg)

**Comment by kommander** [comment]
Wird sich aendern wenn wir auf den custom tile server umgestellt haben. Dort sind die Stadtnamen in der jeweiligen Laendersprache.

**Comment by kommander** [comment]
Scheint wohl ein openmaptiles Daten Problem zu sein :/

**Comment by DanielHabenicht** [comment]
@kommander Scheint jetzt zu funktionieren, habt ihr noch etwas daran geändert?
![image](https://user-images.githubusercontent.com/13590797/97118031-0ff7b000-1708-11eb-9fa2-44417d650949.png)

**Comment by kommander** [comment]
@DanielHabenicht Nein, haben nichts an den Daten gaendert, nur einen anderen style verwendet. Ich schliesse das mal, da es funktioniert.
