### ISSUE TITLE
Navigationhistorie nutzen

### ISSUE THREAD

**Issue by DanielHabenicht** [CovOpen/CovMapper#156]
Bis jetzt gibt es nur eine generelle Kartenansicht auf die der Nutzer aus der Historie (z.B. Back button in "About" Page) zurückspringt. Dabei wird er allerdings nicht auf den vorher ausgewählten Landkreis verwiesen sonder auf seinen vorher gesetzten Postleitzahlkreis. 

Wünschwenswert wäre wenn der gerade ausgewählte Landkreis in der URL persistiert wird um die Browserhistorie zu nutzen den Nutzer auf den vorher ausgewählten Landkreis zurückzuführen. 

Am Beispiel: 
(gesetzter Landkreis: Dresden) 
Bisher: "wählt Berlin aus" -> "besucht About Page" -> "navigiert zurück" -> "sieht Landkreis Dresden"
Erwünscht: "wählt Berlin aus" -> "besucht About Page" -> "navigiert zurück" -> "sieht Berlin"

Notes: 
Das gleich wäre auch für den Status der UI wünschenswert, ergo ob das Fenster für den Landkreis gerade ausgeklappt ist oder nicht.

**Comment by ChristophWersal** [comment]
Hierfür gibt es bereits einen Task in Trello -> alle Unterseiten als Modals anzeigen. Dann bleibt die Karte im Hintergrund bestehen und muss auch nicht neu geladen/aufgebaut werden.

**Comment by DanielHabenicht** [comment]
Genau, aber ich denke das verschiebt das Problem nur. Wenn ich dann von der Karte nach vorne navigieren, weil ich wieder zurück auf die Seite will löst der modal das Problem nicht.

**Comment by kommander** [comment]
@DanielHabenicht so wie in #180 vorgeschlagen geht vor/zurueck mit den browser buttons (wenn die z-indizes stimmen)

**Comment by DanielHabenicht** [comment]
Jap, ich finde der PR ist auf einen guten Weg. Was nicht funktioniert ist das beim neuladen der ausgewählte Landkreis erhalten bleibt und auch nicht der Status der Infobox (ausgeklappt/eingeklappt).
