### ISSUE TITLE
all menu pages have no back button 

### ISSUE THREAD

**Issue by DanielHabenicht** [CovOpen/CovMapper#213]
Die Seiten im Menü sollten auch noch mit einem Back Button ausgestattet werden, sonst weiß man als Nutzer auch dort nicht so richtig wie man zurückkommt.
![image](https://user-images.githubusercontent.com/13590797/96932219-d718ca80-14be-11eb-834d-69d6b6bd9340.png)
Bei den Graphen gibt es gar keine überschrift.
![image](https://user-images.githubusercontent.com/13590797/96932373-12b39480-14bf-11eb-9f02-2200a9a21957.png)

**Comment by kommander** [comment]
Kann man das vielleicht mit einem wrapper fuer page components machen? Da die ja alles gleich gerendert werden, dann haben die Seiten per base app automatisch einen back button und man muss das nicht auf jeder Seite manuell machen.

**Comment by DanielHabenicht** [comment]
Man könnte auch den Titel aus der Page Configuration auslesen, dann muss man nicht mal den überall doppelt hinschreiben :)

**Comment by ChristophWersal** [comment]
Sorry, ich habe eure Kommentare nicht gesehen und es etwas anders gelöst. Aber ich verwende eine gemeinsame Titel-Komponente, die jede Unterseite verwendet. Siehe verlinkter PR.

**Comment by kommander** [comment]
Beim "Den Titel aus der config nehmen" bin ich mir nicht so sicher, das ist ja der Titel für den Menü Eintrag. Dort möchte man vielleicht was anderes haben als auf der Seite selbst.
