### ISSUE TITLE
Thread: Design / UX issues

### ISSUE THREAD

**Issue by DanielHabenicht** [CovOpen/CovMapper#214]
All on Chrome 86 / Windows 10
Graphical Bugs:
- [x] https://test.covmap.de/#/contact-behavior
       ![image](https://user-images.githubusercontent.com/13590797/96933451-bea9af80-14c0-11eb-8465-87a553b1e8ba.png)
- [x] Arrows not centered
       ![image](https://user-images.githubusercontent.com/13590797/96933525-e6007c80-14c0-11eb-8ca9-537bdb520eaf.png)
- [x] non self explanatory button, should be something like "Verhaltenseregeln anzeigen"
       ![image](https://user-images.githubusercontent.com/13590797/96933608-0cbeb300-14c1-11eb-9c84-1f50a46b7b7f.png)
- [x] duplicated text
      ![image](https://user-images.githubusercontent.com/13590797/96933969-baca5d00-14c1-11eb-8440-c6bd0afca187.png)
- [x] the logo in the navbar does not link to the home page
     ![image](https://user-images.githubusercontent.com/13590797/96935094-b1da8b00-14c3-11eb-8b82-37e3fb66559f.png)
- [x] Navigiert man direkt auf eine Seite (z.B. https://test.covmap.de/#/contact-behavior) funktioniert der Back Button nicht

**Comment by ChristophWersal** [comment]
Der erste Text und der Link auf dem Logo sind bereits in 180 und 205 gefixt.
Der doppelte Text bei rechtlichem war genau so gewünscht, da wir es gleich machen sollen wie in der CovApp.

**Comment by DanielHabenicht** [comment]
@ChristophWersal @alexanderthieme Wie wäre es den Teil genauso zu formatieren wie den Rest?
![image](https://user-images.githubusercontent.com/13590797/97416134-59155300-1906-11eb-8493-d25ac92724cd.png)

**Comment by DanielHabenicht** [comment]
closed by #316
