### ISSUE TITLE
Intro - Postal code input field is blocked if map data cannot be loaded

### ISSUE THREAD

**Issue by ChristophWersal** [CovOpen/CovMapper#348]
**Describe the bug**
Opening the app on a fresh browser (clear history) when the data for the map cannot be loaded "Keine Daten für den ausgewählten Zeitraum." leads to the postal code field on the last intro screen to be blocked (nothing can be entered).

**Comment by kantimam** [comment]
looks like he displays it in a dialog so most likely is a zIndex issue.
I try to fix it :)

**Comment by kantimam** [comment]
Don't seem to be able to reproduce it by always having the "Keine Daten für den ausgewählten Zeitraum." dialog open.
Maybe it only happens when "fail" dialog modal is inserted while the WelcomeStepsModal is already open...

**Comment by kantimam** [comment]
looks like problem was focus hijacking of the "fail" modal "disableEnforceFocus" fixes that.
