### ISSUE TITLE
Title of "Deutschlandweite Graphen" is not formated pretty well

### ISSUE THREAD

**Issue by jnnwnk** [CovOpen/CovMapper#358]
**Describe the bug**
The title of "Deutschlandweite Graphen" is centered and contains a line break. The arrow to navigate back is also centered.

**To Reproduce**
Open page http://localhost:8080/#/charts

**Expected behavior**
The title and the arrow should be left aligned without any line break (like on other pages)

**Screenshots**
![image](https://user-images.githubusercontent.com/10629407/98210837-80d96c00-1f41-11eb-9d5b-3181bebb8429.png)

Example for well formated title:
![image](https://user-images.githubusercontent.com/10629407/98210892-92227880-1f41-11eb-933b-aebd5da2a1df.png)

- OS: Win 10
- Browser chrome
- Version 86.0.4240.183

**Comment by DanielHabenicht** [comment]
By fixing this we should also fix the lengthy titles, which do break a little bit odd on mobile devices![Screenshot_20201105_131125_com.android.chrome.jpg](https://user-images.githubusercontent.com/13590797/98239559-6cf53080-1f68-11eb-8c20-7271ad7a5372.jpg)

**Comment by jnnwnk** [comment]
@kantimam this is also fixer by PR #362, isn't it? So we shoul close it, right?

**Comment by kantimam** [comment]
> @kantimam this is also fixer by PR #362, isn't it? So we shoul close it, right?

ja sollte fixed sein, aber hab es live noch nicht ausprobiert. Schließe diesen Issue sobald ich es getestet hab

**Comment by kantimam** [comment]
looks fixed to me :) closing this issue
