### ISSUE TITLE
Please list all people that should be mentioned 

### ISSUE THREAD

**Issue by DanielHabenicht** [CovOpen/CovMapper#72]

**Comment by DanielHabenicht** [comment]
@kommander @ChristianRomberg @m-pa @kantimam @dbartholomae @ChristophWersal 

please write back here if you want to be named in the about page of the app.

@alexanderthieme please also contact and name other persons who contributed not with code (e.g. design, planning, ideation) so we can add them

**Comment by onouv** [comment]
Yes, I would appreciate if you would kindly include me in the contributor mentions. Thankyou.

**Comment by dbartholomae** [comment]
Happy to be mentioned

**Comment by kantimam** [comment]
Would like to be mentioned too :)

**Comment by ChristophWersal** [comment]
Same for me - happy to appear in the list

**Comment by ttobollik** [comment]
Me too : )

**Comment by DanielHabenicht** [comment]
@all-contributers please add @ttobollik for code

**Comment by kommander** [comment]
mich und m-pa bitte auch mit aufnehmen

**Comment by cnrun** [comment]
+1 🙏🏻

**Comment by m-pa** [comment]
Great job everyone! This has really come a long way. Mention would be greatly appreciated. 😄

**Comment by ManuelB** [comment]
Please also list me: @ManuelB - Manuel Blechschmidt

**Comment by DanielHabenicht** [comment]
@ManuelB @cnrun youve been added. 

@m-pa you are also in the list, would you like to share your fullname for mention?

**Comment by baskle** [comment]
Hello, I would also be very happy about a mention. I contributed to the user experience and design, and drew the illustrations and some of the customize icons :)
Full name: Bastian Klenow

**Comment by zwischenmoment** [comment]
Hello, would be very happy about a mention.
Full name: Cornelia Furkert

Do you need a mail adress as well?

**Comment by DanielHabenicht** [comment]
@zwischenmoment @baskle added both of you

**Comment by Japhilko** [comment]
Great work everybody. I contributed a bit in the beginnig (first version of the map) and would be very happy if you would mention me. 
Full Name: Jan-Philipp Kolb

**Comment by sheraben** [comment]
Hi everybody, 

Very nice. I would also be very happy about a mention. Thanks a lot. 

Full Name : Shéhérazade Benzerga

**Comment by DanielHabenicht** [comment]
@sheraben what did you do so I can add the appropriate [contribution key](https://allcontributors.org/docs/en/emoji-key)

**Comment by DanielHabenicht** [comment]
@all-contributers add @sheraben for code

**Comment by DanielHabenicht** [comment]
@all-contributors please add @sheraben

**Comment by DanielHabenicht** [comment]
sry for taking over this pr to try it out

**Comment by DanielHabenicht** [comment]
@all-contributors please add @sheraben for code

**Comment by DanielHabenicht** [comment]
@all-contributors please add @Japhilko for code

**Comment by undheitergehts** [comment]
Hello, would be very happy about a mention.
Full name: Felix Zimmermann

**Comment by DanielHabenicht** [comment]
@all-contributors please add @Japhilko for code

**Comment by DanielHabenicht** [comment]
@Japhilko @sheraben @undheitergehts added you manually in #324

**Comment by jnnwnk** [comment]
Would also be happy to be mentioned. 🙂 
Full name: Janna Wieneke

@DanielHabenicht Is the bot working? Otherwise I could create a PR on my own?

**Comment by DanielHabenicht** [comment]
yep seems like it is broken otherwise it would create the PR for me
