### ISSUE TITLE
Set no-cache header in index.html in NGINX

### ISSUE THREAD

**Issue by DanielHabenicht** [CovOpen/CovMapper#84]

**Comment by kommander** [comment]
We need to check what the CDN does, which currently caches everything. It seems to purposely overwrite the cache headers coming from nginx. If the CDN respects the cache headers from nginx, all index.html requests would hit the webserver. We need to check the CDN settings with Alexander, maybe pair on this today?

**Comment by kommander** [comment]
Fixed
